### ISSUE TITLE
The organisation would like a report on the population of people and those living and not living in cities with a region

### ISSUE THREAD

**Issue by Gavala97** [gabrifili-napier/SET084032021-2TR2001#27]
A report containing the following columns

The name of the continent/region/country.
The total population of the continent/region/country.
The total population of the continent/region/country living in cities (including a %).
The total population of the continent/region/country not living in cities (including a %).

**Comment by JamesMcFaul** [comment]
Provide a report on  The population of people, people living in cities, and people not living in cities in each region
