### ISSUE TITLE
The organisation would like a report on the languages spoken from Largest to smallest and what percentage that is compared to world population.

### ISSUE THREAD

**Issue by Gavala97** [gabrifili-napier/SET084032021-2TR2001#30]
provide the number of people who speak the following the following languages from greatest number to smallest, including the percentage of the world population:

- Chinese.
- English.
- Hindi.
- Spanish.
- Arabic.

**Comment by JamesMcFaul** [comment]
Provide a report on the languages above and how many people speak this language with a percentage value against world population.
